# Generated by Django 2.1.3 on 2019-01-31 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsite', '0002_comment_newspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstTeamScore', models.IntegerField()),
                ('secondTeamSocre', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.CharField(max_length=10)),
                ('weigth', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('yellowCard', models.IntegerField()),
                ('redCard', models.IntegerField()),
                ('biography', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='year',
        ),
        migrations.AddField(
            model_name='teamdata',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamdata',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsite.TeamData'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='sportsite.TeamData'),
        ),
    ]
